spring:
  application:
    name: spring-web-service-sandbox
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/sandbox
    username: sandbox
    password: sandbox
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,env,loggers,mappings,scheduledtasks,httpexchanges,beans,prometheus
  info:
    env:
      enabled: true

pricing:
  catalogue:
    base-url: http://localhost:8081
    username: catalogue-user
    password: secret
    skip-ssl: false

info:
  app:
    name: Spring Boot Sandbox
    description: Sandbox for experimenting with Spring Boot features
